### ISSUE TITLE
Multiple ChatID and USSD

### ISSUE THREAD

**Issue by p152** [telegram-sms/telegram-sms#12]
Hello, you can make it possible to add several ChatID and add ussd commands. (to check the balance)

**Comment by qwe7002** [comment]
Hello, My friend have already replied to you on behalf of myself in the forum, this is a feature request, please do not send it here.

Due to privacy and security issues, you can not speicify multiple chat id.

For ussd, the app is unable to get the response due to the Android limitation.

If you do need to set up multiple chat id, you can change the package name and run all with different chat id. Or, use tools like virtualxposed or shelter to ran multiple version of the same app.

(* you can always change the source code to suit your need)

**Comment by p152** [comment]
Thank you very much for your reply.
